### ISSUE TITLE
"mingw32-make" is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by cyraid** [balena-io-modules/node-ext2fs#60]
I'm on Windows, and have the build tools installed. I don't have MingW installed but it's trying to use "mingw32-make" trying to build libext2fs from ext2fs.cvxproj (in binding.gyp). Could this not be edited to just 'make'? Or a detect for MingW vs nmake (from VS)?

**Comment by zvin** [comment]
No need to build anything starting from v3.0.3, just `npm install ext2fs`
