### ISSUE TITLE
Building with npm 6.4.0 on Windows throws linker errors.

### ISSUE THREAD

**Issue by cedricve** [balena-io-modules/node-ext2fs#74]
Trying to build this using node 11.15.0 and npm 6.4.0. But throws linking error when trying to compile on windows. Please see this issue for more information. https://github.com/balena-io-modules/resin-image-fs/issues/46

<img width="1133" alt="Screenshot 2020-01-06 at 16 13 14" src="https://user-images.githubusercontent.com/1546779/71876761-d4afd480-3127-11ea-912c-6a2fcdd8fe89.png">

Any idea?

**Comment by zvin** [comment]
No need to build anything starting from v3.0.3, just `npm install ext2fs`
